import { MaterialCategory } from "../types/material";

export const materialCategories: MaterialCategory[] = [
  {
    id: 1,
    name: "Seile",
    icon: "images/seil.png",
    materials: [
      {
        id: 1,
        name: "Dynamic Rope X",
        producer: "Rope Inc.",
        type: "Dynamisch",
        dateOfProduction: new Date("2023-01-15"),
        serialNumber: "DR12345",
        firstUse: new Date("2023-02-01"),
        condition: "very good",
        dateOfLastCheck: new Date("2023-05-20"),
        nextCheck: new Date("2023-11-20"),
        signatureOfChecker: "Max Mustermann",
      },
      {
        id: 2,
        name: "Static Rope Y",
        producer: "Climb Safe",
        type: "Statisch",
        dateOfProduction: new Date("2022-08-30"),
        serialNumber: "SR54321",
        firstUse: new Date("2022-09-15"),
        condition: "good",
        dateOfLastCheck: new Date("2023-03-22"),
        nextCheck: new Date("2023-09-22"),
        signatureOfChecker: "Eva Schmidt",
      },
    ],
  },
  {
    id: 2,
    name: "Gurte",
    icon: "images/gurt.png",
    materials: [
      {
        id: 3,
        name: "Astro Bod Fast",
        producer: "Safety First",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "very good",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
    ],
  },
  {
    id: 3,
    name: "Abseilgeräte/ Sicherungsgeräte",
    icon: "images/seilklemme.jpg",
    materials: [
      {
        id: 4,
        name: "Rig",
        producer: "Petzl",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "good",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
    ],
  },
  {
    id: 4,
    name: "mitlaufende Auffanggeräte",
    icon: "images/auffanggerät.jpg",
    materials: [
      {
        id: 5,
        name: "ASAP Lock",
        producer: "Petzl",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "bad",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
    ],
  },
  {
    id: 5,
    name: "Seilklemmen",
    icon: "images/seilklemme.jpg",
    materials: [
      {
        id: 6,
        name: "Ascension",
        producer: "Petzl",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "very good",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
    ],
  },
  {
    id: 6,
    name: "Seilrollen",
    icon: "images/seilrolle.png",
    materials: [
      {
        id: 7,
        name: "Spin S1",
        producer: "Petzl",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "very good",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
      {
        id: 8,
        name: "Pro Traxion",
        producer: "Petzl",
        type: "mit Rücklaufsperre",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "very good",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
    ],
  },
  {
    id: 7,
    name: "Anschlagmittel",
    icon: "images/anschlagmittel.png",
    materials: [
      {
        id: 9,
        name: "Wire Strop",
        producer: "Petzl",
        type: "60cm",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "very good",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
      {
        id: 10,
        name: "Anneau",
        producer: "Petzl",
        type: "120cm",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "very good",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
    ],
  },
  {
    id: 8,
    name: "Karabiner",
    icon: "images/karabiner.png",
    materials: [
      {
        id: 11,
        name: "OK",
        producer: "Petzl",
        type: "Ball-Lock",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "very good",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
      {
        id: 12,
        name: "OK",
        producer: "Petzl",
        type: "Screw-Lock",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "very good",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
      {
        id: 3,
        name: "OK",
        producer: "Petzl",
        type: "Tri-Lock",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "very good",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
    ],
  },
  {
    id: 9,
    name: "Verbindungsmittel/ Falldämpfer",
    icon: "images/verbindungsmittel.jpg",
    materials: [
      {
        id: 13,
        name: "Grillon",
        producer: "Petzl",
        type: "5m",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "good",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
      {
        id: 14,
        name: "Grillon",
        producer: "Petzl",
        type: "3m",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "bad",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
      {
        id: 15,
        name: "Absorbica",
        producer: "Petzl",
        dateOfProduction: new Date("2022-12-25"),
        serialNumber: "FBH67890",
        firstUse: new Date("2023-01-20"),
        condition: "exchange",
        dateOfLastCheck: new Date("2023-06-10"),
        nextCheck: new Date("2023-12-10"),
        signatureOfChecker: "Johann Bauer",
      },
    ],
  },
  // Weitere Kategorien und Materialien hinzufügen
];
